title: xJupitar's Portfolio
description: **Welcome to my portfolio**, 
Here I highlight my extensive expertise in blockchain technology and cryptocurrency innovation. I bring over seven years of dedicated experience in driving community engagement, managing decentralized projects, and advancing blockchain infrastructure. Explore my journey, from community leadership to running validators node.
theme: jekyll-theme-minimal
